

export const metadata: Metadata = {
  title: {
    default: "OpenTable",
    template: "%s",
  },
  description: "Generated by create next app",
};

import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";


const inter = Inter({ subsets: ["latin"] });



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='bg-gray-100 min-h-screen w-screen'>
          <div className='max-w-screen-2xl m-auto bg-white'>
            <NavBar />
            {children}
           
          </div>
        </main>
      </body>
    </html>
  );
}
